meta:
  description: farmr
  vendor: farmr
  maintainer: farmr
files:
  "/usr/bin/farmr":
    file: farmr_package
    mode: "0755"
    user: "root"
  "/etc/systemd/user/farmr.service":
    file: .github/workflows/farmr.service
    mode: "0644"
    user: "root"
  "/etc/systemd/user/farmr-hpool.service":
    file: .github/workflows/farmr-hpool.service
    mode: "0644"
    user: "root"
  "/etc/farmr/config/config-xch.json":
    file: config/config-xch.json
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xch.json":
    file: blockchain/xch.json
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xfx.json.template":
    file: blockchain/xfx.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/cgn.json.template":
    file: blockchain/cgn.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xgj.json.template":
    file: blockchain/xgj.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/spare.json.template":
    file: blockchain/spare.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xse.json.template":
    file: blockchain/xse.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xfl.json.template":
    file: blockchain/xfl.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/hdd.json.template":
    file: blockchain/hdd.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/avo.json.template":
    file: blockchain/avo.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/gdog.json.template":
    file: blockchain/gdog.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/apple.json.template":
    file: blockchain/apple.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/tad.json.template":
    file: blockchain/tad.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xdg.json.template":
    file: blockchain/xdg.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xka.json.template":
    file: blockchain/xka.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xmz.json.template":
    file: blockchain/xmz.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xtx.json.template":
    file: blockchain/xtx.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/tsit.json.template":
    file: blockchain/tsit.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/cac.json.template":
    file: blockchain/cac.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xcd.json.template":
    file: blockchain/xcd.json.template
    mode: "0644"
    user: "root"
    keep: true
units:
  #- .github/workflows/farmr.service
scripts:
  "post-install": .github/workflows/post-inst
user: foo